@startuml
start
:Order Orchestrator;

fork
    :Order Service;
	:process;
fork again
	:Payment Service;
	:process;
fork again
	:Restaurant Service;
	:process;
fork again
	:Delivery Service;
	:process;
end fork
if (OK) then
   :Done;
else
   :Error;
   detach
endif
stop

@enduml